"""
config.py — Centralized configuration for the Farm Bot automation.
All paths, timings, and tunables live here. Change once, apply everywhere.

SHARING NOTE: User-specific paths (GnBots, LDPlayer) live in user_config.py,
which is .gitignored. This file contains only defaults. When someone clones
the repo, they run setup_farm_bot.py which generates their user_config.py.
"""

from pathlib import Path
import ctypes
import sys
import os

# Initialize DPI Awareness immediately so all coordinate queries (including monitor positions)
# return correct physical screen pixel coordinates.
try:
    ctypes.windll.shcore.SetProcessDpiAwareness(2) # 2 = PROCESS_PER_MONITOR_DPI_AWARE
except Exception:
    try:
        ctypes.windll.user32.SetProcessDPIAware()
    except Exception:
        pass

# ──────────────────────────────────────────────
#  Paths (defaults — overridden by user_config.py)
# ──────────────────────────────────────────────
# Base project directory (wherever this script lives)
PROJECT_DIR = Path(__file__).resolve().parent

# External application paths — DEFAULT PLACEHOLDERS.
# The actual paths come from user_config.py (generated by setup_farm_bot.py).
# If user_config.py doesn't exist, these defaults will be used (and likely fail validation).
GNBOTS_PATH = Path(r"C:\Program Files\GnBots\GnBots.exe")
LDPLAYER_PATH = Path(r"C:\LDPlayer\LDPlayer9\dnplayer.exe")
LDMULTIPLAYER_PATH = Path(r"C:\LDPlayer\LDPlayer9\dnmultiplayer.exe")



# Project subdirectories
TEMPLATE_DIR = PROJECT_DIR / "templates"
SCREENSHOT_DIR = PROJECT_DIR / "screenshots"
LOG_DIR = PROJECT_DIR / "logs"
LOG_FILE = LOG_DIR / "FarmLog.txt"

# ──────────────────────────────────────────────
#  GnBots Window
# ──────────────────────────────────────────────
GNBOTS_TITLE = "Goodnight Bots"

# ──────────────────────────────────────────────
#  Process Kill List
# ──────────────────────────────────────────────
KILL_TARGETS = [
    "GnBots.exe",
]

LDPLAYER_TARGETS = [
    "dnplayer.exe",
    "Ld9BoxHeadless.exe",
    "Ld9BoxSVC.exe",
]

KILL_EMULATOR_TOO = True

# ──────────────────────────────────────────────────────────────
#  Image Detection Overrides (No longer used, fully keyboard-driven)
# ──────────────────────────────────────────────────────────────

# ──────────────────────────────────────────────
#  Second Monitor Position
# ──────────────────────────────────────────────
import win32api
import win32con

def get_opposite_monitor_coords():
    """Detect and return the top-left coordinates of the opposite (secondary) monitor.

    If VDD_PREFER is True, prefer virtual displays over physical ones.
    Defaults to (0, 0) if only one monitor is present.
    """
    try:
        monitors = win32api.EnumDisplayMonitors()
        if len(monitors) > 1:
            virtual_coords = None
            physical_coords = None

            for hMonitor, _, rect in monitors:
                info = win32api.GetMonitorInfo(hMonitor)
                is_primary = info.get("Flags", 0) & win32con.MONITORINFOF_PRIMARY
                if not is_primary:
                    device_name = info.get("Device", "")
                    is_virtual = any(keyword in device_name.lower() for keyword in
                                     ["idd", "virtual", "rooted", "mirage"])

                    if is_virtual:
                        virtual_coords = (rect[0], rect[1])
                    else:
                        physical_coords = (rect[0], rect[1])

            if VDD_PREFER and virtual_coords is not None:
                return virtual_coords
            elif physical_coords is not None:
                return physical_coords
            elif virtual_coords is not None:
                return virtual_coords
    except Exception:
        pass
    return 0, 0

MONITOR2_X, MONITOR2_Y = get_opposite_monitor_coords()

# ──────────────────────────────────────────────
#  Timing (seconds)
# ──────────────────────────────────────────────
KILL_WAIT = 2
GNBOTS_LAUNCH_WAIT = 10
CLICK_DELAY = 0.5
DIALOG_WAIT = 5
LDPLAYER_BOOT_WAIT = 45
LDPLAYER_INSTANCE = 0

# ──────────────────────────────────────────────
#  Template Matching
# ──────────────────────────────────────────────
TEMPLATE_MATCH_THRESHOLD = 0.75
TEMPLATE_FALLBACK_THRESHOLD = 0.60
TEMPLATE_MULTI_SCALE = True
TEMPLATE_SCALES = [0.75, 0.8, 0.85, 0.9, 0.95, 1.0, 1.05, 1.1, 1.15, 1.2, 1.25, 1.3]

# ──────────────────────────────────────────────
#  Retry Settings
# ──────────────────────────────────────────────
MAX_RETRIES = 5
RETRY_DELAY = 3

# ──────────────────────────────────────────────
#  Screenshot Differencing
# ──────────────────────────────────────────────
DIFF_THRESHOLD = 5.0
DIFF_SAVE_ALL = True
DIFF_DIR = SCREENSHOT_DIR / "diffs"

# ──────────────────────────────────────────────
#  Click Verification
# ──────────────────────────────────────────────
VERIFY_CLICK = False

# ──────────────────────────────────────────────
#  Monitoring
# ──────────────────────────────────────────────
HEALTH_CHECK_INTERVAL = 300
HEALTH_CHECK_METHOD = "process"
HEALTH_CHECK_ON_FAIL = "kill_and_report"
DETECT_COMPLETION = False
COMPLETION_CHECK_INTERVAL = 120
COMPLETION_TEMPLATE = TEMPLATE_COMPLETED
COMPLETION_WINDOW_TITLE = None
RUN_DURATION = 7200

# ──────────────────────────────────────────────
#  Self-Elevation
# ──────────────────────────────────────────────
AUTO_ELEVATE = True

# ──────────────────────────────────────────────
#  Headless Mode
# ──────────────────────────────────────────────
HEADLESS = False

# ──────────────────────────────────────────────
#  Ghost Mode (Window Transparency)
# ──────────────────────────────────────────────
GHOST_MODE = False
GHOST_ALPHA = 0
GHOST_WHEN = "after_enter"

# ──────────────────────────────────────────────
#  Virtual Display Detection
# ──────────────────────────────────────────────
VDD_PREFER = True

# ──────────────────────────────────────────────
#  Log Rotation
# ──────────────────────────────────────────────
LOG_MAX_BYTES = 5 * 1024 * 1024
LOG_BACKUP_COUNT = 3

# ──────────────────────────────────────────────
#  Notifications (defaults — overridden by user_config.py)
# ──────────────────────────────────────────────
NOTIFICATIONS = {
    "webhook_url": None,
    "webhook_enabled": False,
    "desktop_enabled": False,
    "on_cycle_start": True,
    "on_cycle_complete": True,
    "on_error": True,
    "on_health_fail": True,
    "on_completion_detected": True,
    "sound_file": None,
}

# ──────────────────────────────────────────────
#  Coordinate Fallback
# ──────────────────────────────────────────────
COORD_FALLBACK_ENABLED = True

COORD_FALLBACKS = {
    "start_btn": None,
    "first_btn": None,
    "continue_btn": None,
}

# ──────────────────────────────────────────────
#  ADB Settings (future use)
# ──────────────────────────────────────────────
ADB_HOST = "127.0.0.1"
ADB_PORT = 5037

# ──────────────────────────────────────────────
#  Load user overrides
# ──────────────────────────────────────────────
# user_config.py is .gitignored and generated by setup_farm_bot.py.
# It overrides the defaults above with the user's actual paths and preferences.
# Must be at the very end so it overrides all defaults defined above.
_USER_CONFIG_PATH = PROJECT_DIR / "user_config.py"
if _USER_CONFIG_PATH.exists():
    # Read and exec the user config, then update this module's globals
    _user_globals = {}
    with open(_USER_CONFIG_PATH, 'r', encoding='utf-8') as _f:
        exec(compile(_f.read(), str(_USER_CONFIG_PATH), 'exec'), _user_globals)
    # Apply only the keys that exist in both this module and user_config
    for _key, _value in _user_globals.items():
        if not _key.startswith('_') and _key.isupper():
            globals()[_key] = _value
